blank_issues_enabled: true
contact_links:
  - name: Quick start guide
    url: https://github.com/screenreaders/soft-braille-keyboard/blob/main/README
    about: Build, install and reporting information for Soft Braille Keyboard.
